# -*- coding: utf-8 -*-
"""DATA STRUCTURE 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TVpmDidScBdsXQL-875WQPLzborNxAd
"""

size =int(input("Masukkan ukuran peta: "))

treasure_map = ["_" for _ in range(size)]

print(f"selamat datang di Treasure Hunt ! Peta memiliki {size} lokasi (0 hingga {size-1}). ")
treasure_index = random.randint(0, size-1)
print(f"Harta karun telah disembunyikan di lokasi acak. Cobalah untuk menemukannya!")
while treasure_index < 0 or treasure_index >= size:
  print("Lokasi tidak valid. Masukkan angka dalam rentan yang benar.")
  treasure_index = int(input(f"Masukan lokasi harta karun (0 hingga {size-1}): "))

treasure_map[treasure_index] = "X"

def play_treasure_hunt():
  print ("\nHarta karun telah disembunyikan! Sekarang giliran pemain menebak")
  print ("Cobalah untuk menemukan harta karun dengan menebak indeks yang benar.")
  while True:
    print ("\nPeta saat ini: ", ["_" for _ in range(size)])
    try:
      guess = int(input(f"Masukkan indeks tebakanmu (0 hingga {size-1}): "))
    except ValueError:
      print("Masukkan angka yang valid.")
      continue

    if guess < 0 or guess >= size:
      print("Indeks tidak valid, pilih antara 0 hingga", size-1)
      continue

    if treasure_map[guess] == "X":
      print("Selamat! Kamu menemukan harta karun di lokasi:", guess)
      break
    else:
      print("Tidak ada harta di lokasi ini. Coba lagi!")

play_treasure_hunt()
